-- AlterTable
ALTER TABLE "User" ADD COLUMN "avatarFace" TEXT NOT NULL DEFAULT 'cool';
ALTER TABLE "User" ADD COLUMN "avatarJersey" TEXT NOT NULL DEFAULT 'lime';
ALTER TABLE "User" ADD COLUMN "avatarCap" TEXT NOT NULL DEFAULT 'cap';
ALTER TABLE "User" ADD COLUMN "avatarFrame" TEXT NOT NULL DEFAULT 'lime';
ALTER TABLE "User" ADD COLUMN "avatarRole" TEXT NOT NULL DEFAULT 'bat';
ALTER TABLE "User" ADD COLUMN "avatarNumber" INTEGER NOT NULL DEFAULT 7;
